# This is a basic workflow to help you get started with Actions

name: rootfs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kernel:
    runs-on: ubuntu-latest
    strategy:
            matrix:
                version: [sc7280-6.19.y]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: sudo apt update && sudo apt install build-essential gcc-aarch64-linux-gnu bc flex bison 7zip-standalone zstd kmod bash cpio binutils tar git wget dpkg libssl-dev -y

      - name: Build
        run: sudo sh $PWD/scripts/kernel_build.sh

      - name: Upload deb packages
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: nothing-spacewar-debs_${{ matrix.version }}
          path: ${{ github.workspace }}/*.deb
          
  rootfs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: kernel
    strategy:
            matrix:
                desktop: [ubuntu-desktop]
                kernel: [sc7280-6.19.y]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: nothing-spacewar-debs*
      - name: Install Dependencies
        run: sudo apt update && sudo apt install build-essential gcc-aarch64-linux-gnu bc flex bison 7zip-standalone zstd kmod bash cpio binutils tar git wget dpkg libssl-dev -y

      - name: Build rootfs
        run: sudo sh $PWD/scripts/rootfs_build.sh ${{ matrix.desktop }} ${{ matrix.kernel }}

      - name: Upload rootfs.7z
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: rootfs_${{ matrix.desktop }}_${{ matrix.kernel }}
          path: rootfs.7z
          compression-level: 0
